import Link from "next/link";

export default function Home() {
  return (
    <main className="min-h-screen bg-gradient-to-br from-slate-950 via-purple-950 to-slate-950 text-white overflow-hidden">
      {/* Animated background orbs */}
      <div className="fixed inset-0 overflow-hidden pointer-events-none">
        <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-purple-500/20 rounded-full blur-3xl animate-pulse"></div>
        <div className="absolute bottom-1/4 right-1/4 w-96 h-96 bg-indigo-500/20 rounded-full blur-3xl animate-pulse delay-1000"></div>
        <div className="absolute top-1/2 left-1/2 w-64 h-64 bg-pink-500/10 rounded-full blur-3xl animate-pulse delay-500"></div>
      </div>
      
      {/* Hero Section */}
      <div className="relative container mx-auto px-4 py-20">
        <div className="text-center max-w-4xl mx-auto">
          <div className="inline-flex items-center gap-2 px-4 py-2 bg-white/10 backdrop-blur rounded-full text-sm text-purple-200 mb-8 border border-white/10">
            <span className="relative flex h-2 w-2">
              <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-green-400 opacity-75"></span>
              <span className="relative inline-flex rounded-full h-2 w-2 bg-green-500"></span>
            </span>
            Generated by Architex AI
          </div>
          
          <h1 className="text-6xl md:text-7xl font-bold mb-6 bg-gradient-to-r from-white via-purple-200 to-indigo-200 bg-clip-text text-transparent leading-tight">
            Projects-dashboard
          </h1>
          
          <p className="text-xl text-gray-300 mb-12 max-w-2xl mx-auto leading-relaxed">
            project dashboard for a bunch of projects
          </p>
          
          <div className="flex gap-4 justify-center flex-wrap">
            <Link 
              href="/dashboard" 
              className="group px-8 py-4 bg-gradient-to-r from-purple-600 to-indigo-600 rounded-xl font-semibold hover:from-purple-500 hover:to-indigo-500 transition-all duration-300 shadow-lg shadow-purple-500/25 hover:shadow-purple-500/40 hover:scale-105"
            >
              Open Dashboard
              <span className="inline-block ml-2 group-hover:translate-x-1 transition-transform">→</span>
            </Link>
            <Link 
              href="/projects" 
              className="px-8 py-4 border border-white/20 rounded-xl font-semibold hover:bg-white/10 transition-all duration-300 backdrop-blur"
            >
              View Projects
            </Link>
          </div>
        </div>
        
        {/* Feature Cards */}
        <div className="mt-24 grid grid-cols-1 md:grid-cols-3 gap-6 max-w-5xl mx-auto">
          
          <div className="group p-6 rounded-2xl bg-white/5 backdrop-blur border border-white/10 hover:bg-white/10 hover:border-purple-500/30 transition-all duration-300 hover:scale-105">
            <div className="w-14 h-14 rounded-xl bg-gradient-to-br from-purple-500/20 to-indigo-500/20 border border-white/10 flex items-center justify-center mb-4 text-2xl group-hover:scale-110 transition-transform">
              ⚡
            </div>
            <h3 className="text-lg font-semibold mb-2 group-hover:text-purple-300 transition-colors">FastAPI</h3>
            <p className="text-gray-400 text-sm leading-relaxed">FastAPI Python REST API</p>
          </div>

          <div className="group p-6 rounded-2xl bg-white/5 backdrop-blur border border-white/10 hover:bg-white/10 hover:border-purple-500/30 transition-all duration-300 hover:scale-105">
            <div className="w-14 h-14 rounded-xl bg-gradient-to-br from-purple-500/20 to-indigo-500/20 border border-white/10 flex items-center justify-center mb-4 text-2xl group-hover:scale-110 transition-transform">
              ⚛️
            </div>
            <h3 className="text-lg font-semibold mb-2 group-hover:text-purple-300 transition-colors">React</h3>
            <p className="text-gray-400 text-sm leading-relaxed">React SPA with Vite bundler</p>
          </div>

          <div className="group p-6 rounded-2xl bg-white/5 backdrop-blur border border-white/10 hover:bg-white/10 hover:border-purple-500/30 transition-all duration-300 hover:scale-105">
            <div className="w-14 h-14 rounded-xl bg-gradient-to-br from-purple-500/20 to-indigo-500/20 border border-white/10 flex items-center justify-center mb-4 text-2xl group-hover:scale-110 transition-transform">
              🐘
            </div>
            <h3 className="text-lg font-semibold mb-2 group-hover:text-purple-300 transition-colors">PostgreSQL</h3>
            <p className="text-gray-400 text-sm leading-relaxed">PostgreSQL database</p>
          </div>
        </div>
        
        {/* Tech Stack Pills */}
        <div className="mt-16 flex justify-center gap-3 flex-wrap">
          
          <span className="px-4 py-2 bg-white/5 backdrop-blur border border-white/10 rounded-full text-sm text-gray-300 hover:bg-white/10 hover:border-purple-500/30 transition-all cursor-default">
            Fastapi
          </span>

          <span className="px-4 py-2 bg-white/5 backdrop-blur border border-white/10 rounded-full text-sm text-gray-300 hover:bg-white/10 hover:border-purple-500/30 transition-all cursor-default">
            React
          </span>

          <span className="px-4 py-2 bg-white/5 backdrop-blur border border-white/10 rounded-full text-sm text-gray-300 hover:bg-white/10 hover:border-purple-500/30 transition-all cursor-default">
            Postgres
          </span>
        </div>
      </div>
      
      {/* Footer */}
      <footer className="relative mt-24 border-t border-white/10 py-8">
        <div className="container mx-auto px-4 text-center text-gray-500 text-sm">
          Built with Architex • Powered by your imagination
        </div>
      </footer>
    </main>
  );
}
